repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: black-auto-fix
        args: [--line-length=88]
        language_version: python3.12
      - id: black
        name: black-check
        args: [--line-length=88, --check]
        language_version: python3.12

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    - id: autoflake
      args: [--remove-all-unused-imports, --in-place, --ignore-init-module-imports, --remove-unused-variables]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
