services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: hpub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localtestingpassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      AWS_DEFAULT_REGION: eu-west-2
      AWS_REGION: eu-west-2
      AWS_ENDPOINT_URL_S3: http://localstack:4566
      AWS_ACCESS_KEY_ID: FAKEACCESSKEYID
      AWS_SECRET_ACCESS_KEY: FAKESECRETACCESSKEY
    ports:
      - "8000:8000"
    volumes:
      - ./health_pubs:/app

  localstack:
    image: localstack/localstack:4.1.1
    environment:
      - SERVICES=s3,secretsmanager,events
      - HOSTNAME=localstack
      - DEBUG=1
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh

volumes:
  pg_data: