# Generated by Django 5.1.4 on 2025-06-04 12:56

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLimitPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "order_limit_id",
                    models.CharField(
                        default=uuid.uuid4, editable=False, max_length=225, unique=True
                    ),
                ),
                ("order_limit", models.PositiveIntegerField()),
                (
                    "full_external_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
