# Generated by Django 5.1.4 on 2025-04-11 12:09

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("products", "0001_initial"),
        ("wagtailcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLimitPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "order_limit_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("order_limit", models.PositiveIntegerField()),
                (
                    "full_external_keys",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "organization_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_limits",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_limits",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
