# Generated by Django 5.1.4 on 2025-05-21 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_limits", "0001_initial"),
        ("wagtailcore", "0095_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderlimitpage",
            name="order_limit_id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=225, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="orderlimitpage",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
        ),
    ]
