name: "Install Dependencies"

description: "Install dependencies for React (npm) and Python projects"

runs:
  using: "composite"
  steps:
    # Set up Node.js for the React frontend
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    # Get npm cache directory path
    - name: Get npm Cache Directory Path
      id: npm_cache_dir_path
      run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      shell: bash

    # Cache npm dependencies
    - uses: actions/cache@v4
      id: npm_cache
      with:
        path: ${{ steps.npm_cache_dir_path.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('hp-frontend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    # Install Node.js dependencies using npm
    - name: Install Node Dependencies
      run: |
        cd hp-frontend || { echo "Directory hp-frontend not found"; exit 1; }
        npm ci
      shell: bash

    # Set up Python for the backend
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.12"

    # Cache Python dependencies
    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('hpub-backend/health_pubs/requirements.txt') }} # Adjusted path
        restore-keys: |
          ${{ runner.os }}-pip-

    # Install Python dependencies
    - name: Install Python Dependencies
      run: |
        cd hpub-backend/health_pubs || { echo "Directory hpub-backend/health_pubs not found"; exit 1; }
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
