# Generated by Django 5.1.4 on 2025-04-11 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("addresses", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        ("wagtailcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "full_external_key",
                    models.CharField(
                        blank=True,
                        help_text="The full external key retrieved from the related establishment.",
                        max_length=25,
                    ),
                ),
                ("order_confirmation_number", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_origin",
                    models.CharField(
                        choices=[
                            ("by_user", "BY_USER"),
                            ("order_on_behalf", "ORDER_ON_BEHALF"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "address_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="addresses.address",
                    ),
                ),
                (
                    "user_ref",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "order_item_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "product_code",
                    models.CharField(default="UNKNOWN", editable=False, max_length=255),
                ),
                ("quantity", models.IntegerField()),
                ("quantity_inprogress", models.IntegerField(default=0)),
                ("quantity_shipped", models.IntegerField(default=0)),
                ("quantity_cancelled", models.IntegerField(default=0)),
                (
                    "order_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="orders.order",
                    ),
                ),
                (
                    "product_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
