# Generated by Django 5.1.4 on 2025-05-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                ("programme_name", models.CharField(max_length=100, unique=True)),
                (
                    "external_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_temporary", models.BooleanField(default=False)),
                (
                    "program_id",
                    models.CharField(
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "program_term",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short_term", "Short Term"),
                            ("long_term", "Long Term"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
