# Generated by Django 5.1.4 on 2025-04-11 12:09

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models
from ..choices import (
    COST_CENTRE_CHOICES,
    LOCAL_CODES_CHOICES,
    PRODUCT_TYPE_CHOICE,
    ALTERNATIVE_TYPE_CHOICE,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audiences", "0001_initial"),
        ("diseases", "0001_initial"),
        ("languages", "0001_initial"),
        ("programs", "0001_initial"),
        ("users", "0001_initial"),
        ("vaccinations", "0001_initial"),
        ("wagtailcore", "0001_initial"),
        ("where_to_use", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUpdate",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("minimum_stock_level", models.IntegerField(blank=True, null=True)),
                ("maximum_order_quantity", models.IntegerField(blank=True, null=True)),
                ("quantity_available", models.IntegerField(blank=True, default=0)),
                ("run_to_zero", models.BooleanField(blank=True, default=False)),
                (
                    "available_from_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("immediately", "Available immediately (allow pre-orders)"),
                            ("specific_date", "On a specific date"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_from_date", models.DateField(blank=True, null=True)),
                (
                    "available_until_choice",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no_end_date", "No End Date"),
                            ("specific_date", "On a specific date"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_end_date", models.DateField(blank=True, null=True)),
                (
                    "product_type",
                    models.CharField(
                        blank=True,
                        choices=PRODUCT_TYPE_CHOICE,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "alternative_type",
                    models.CharField(
                        blank=True,
                        choices=ALTERNATIVE_TYPE_CHOICE,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cost_centre",
                    models.CharField(
                        blank=True,
                        choices=COST_CENTRE_CHOICES,
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "local_code",
                    models.CharField(
                        blank=True,
                        choices=LOCAL_CODES_CHOICES,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("unit_of_measure", models.IntegerField(blank=True, null=True)),
                (
                    "summary_of_guidance",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "product_downloads",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("main_download_url", models.JSONField(blank=True, default=list)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("print_download_url", models.JSONField(blank=True, default=list)),
                ("web_download_url", models.JSONField(blank=True, default=list)),
                ("transcript_url", models.JSONField(blank=True, default=list)),
                (
                    "order_referral_email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "stock_owner_email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "order_exceptions",
                    wagtail.fields.RichTextField(blank=True, null=True),
                ),
                (
                    "audience_ref",
                    models.ManyToManyField(blank=True, to="audiences.audience"),
                ),
                (
                    "diseases_ref",
                    models.ManyToManyField(blank=True, to="diseases.disease"),
                ),
                (
                    "vaccination_ref",
                    models.ManyToManyField(blank=True, to="vaccinations.vaccination"),
                ),
                (
                    "where_to_use_ref",
                    models.ManyToManyField(blank=True, to="where_to_use.wheretouse"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("product_key", models.CharField(max_length=50)),
                (
                    "product_key_testss",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("program_name", models.CharField(max_length=255)),
                ("iso_language_code", models.CharField(max_length=10)),
                ("product_code", models.CharField(max_length=255, unique=True)),
                (
                    "product_code_no_dashes",
                    models.CharField(editable=False, max_length=255, null=True),
                ),
                ("version_number", models.IntegerField()),
                ("product_title", models.CharField(max_length=255)),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("live", "Live"),
                            ("archived", "Archived"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("download-only", "Download Only"),
                            ("download-or-order", "Download or Order"),
                            ("order-only", "Order Only"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("language_name", models.CharField(max_length=30)),
                ("file_url", models.URLField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="languages.languagepage",
                    ),
                ),
                (
                    "program_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="programs.program",
                    ),
                ),
                (
                    "user_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="users.user",
                    ),
                ),
                (
                    "update_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product",
                        to="products.productupdate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
