# Generated by Django 5.1.4 on 2025-04-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_key_testsss",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
