# Generated by Django 5.1.4 on 2025-05-14 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="If not provided, set to now on first save.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="If not provided, set to now on every save.",
            ),
        ),
    ]
