# Generated by Django 5.1.2 on 2025-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdate",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audio", "Audio"),
                    ("Transcript", "Transcript"),
                    ("Bulletins", "Bulletins"),
                    ("Consent Form", "Consent Form"),
                    ("Images", "Images"),
                    ("Leaflets", "Leaflets"),
                    ("Postcards", "Postcards"),
                    ("Posters", "Posters"),
                    ("Pull-up Banners", "Pull-up Banners"),
                    ("Stickers", "Stickers"),
                    ("Record Cards", "Record Cards"),
                    ("Record Card", "Record Card"),
                    ("Z-Card", "Z-Card"),
                    ("Fridge Magnet", "Fridge Magnet"),
                    ("Flyer", "Flyer"),
                    ("Invitation Letter", "Invitation Letter"),
                    ("Alternative", "Alternative"),
                    ("Memoire", "Memoire"),
                    ("Guidance", "Guidance"),
                    ("Video", "Video"),
                    ("GIF", "GIF"),
                    ("Slides", "Slides"),
                    ("Factsheets", "Factsheets"),
                    ("Briefing sheet", "Briefing sheet"),
                    ("Flip Chart", "Flip Chart"),
                    ("Immunisation Schedule", "Immunisation Schedule"),
                    ("Booklet", "Booklet"),
                    ("Envelope Label", "Envelope Label"),
                    ("Pack Sleeve", "Pack Sleeve"),
                    ("Slide", "Slide"),
                    ("Audio Transcript", "Audio Transcript"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
