# Generated by Django 5.1.4 on 2025-05-16 14:46

from django.db import migrations, models
from ..choices import PRODUCT_TYPE_CHOICE


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdate",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=PRODUCT_TYPE_CHOICE,
                max_length=50,
                null=True,
            ),
        ),
    ]
