# Generated by Django 5.1.4 on 2025-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdate",
            name="product_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audio", "Audio"),
                    ("Transcript", "Transcript"),
                    ("Bulletins", "Bulletins"),
                    ("Consent Form", "Consent Form"),
                    ("Images", "Images"),
                    ("Leaflets", "Leaflets"),
                    ("Postcards", "Postcards"),
                    ("Posters", "Posters"),
                    ("Pull-up Banners", "Pull-up Banners"),
                    ("Stickers", "Stickers"),
                    ("Record Cards", "Record Cards"),
                    ("Z-Card", "Z-Card"),
                    ("Fridge Magnet", "Fridge Magnet"),
                    ("Flyer", "Flyer"),
                    ("Alternative", "Alternative"),
                    ("Memoire", "Memoire"),
                    ("Guidance", "Guidance"),
                    ("Video", "Video"),
                    ("GIF", "GIF"),
                    ("Slides", "Slides"),
                    ("Factsheets", "Factsheets"),
                    ("Briefing sheet", "Briefing sheet"),
                    ("Flip Chart", "Flip Chart"),
                    ("Immunisation Schedule", "Immunisation Schedule"),
                    ("Booklet", "Booklet"),
                    ("Envelope Label", "Envelope Label"),
                    ("Pack Sleeve", "Pack Sleeve"),
                    ("Slide", "Slide"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
