# Generated by Django 5.1.2 on 2025-03-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_productupdate_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdate",
            name="alternative_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Video and Audio", "Video and Audio"),
                    ("Simple Text", "Simple Text"),
                    ("Braille", "Braille"),
                    ("Easy read", "Easy read"),
                    ("British Sign Language (BSL)", "British Sign Language (BSL)"),
                    ("Large print", "Large print"),
                    ("not-accessible", "not-accessible"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
