# Generated by Django 5.1.4 on 2025-06-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0003_initial"),
        ("vaccinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productupdate",
            name="vaccination_ref",
            field=models.ManyToManyField(blank=True, to="vaccinations.vaccination"),
        ),
    ]
