# Generated by Django 5.1.2 on 2025-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_productupdate_alternative_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productupdate",
            name="alternative_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Video and Audio", "Video and Audio"),
                    ("Braille", "Braille"),
                    ("Easy read", "Easy read"),
                    ("British Sign Language (BSL)", "British Sign Language (BSL)"),
                    ("Large print", "Large print"),
                    ("Simple Text", "Simple Text"),
                    ("not-accessible", "not-accessible"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productupdate",
            name="available_from_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("immediately", "Available immediately (allow pre-orders)"),
                    ("specific_date", "On a specific date"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productupdate",
            name="available_until_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_end_date", "No End Date"),
                    ("specific_date", "On a specific date"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productupdate",
            name="cost_centre",
            field=models.CharField(
                blank=True,
                choices=[
                    ("10200", "10200"),
                    ("22820", "22820"),
                    ("24839", "24839"),
                    ("25050", "25050"),
                    ("25430", "25430"),
                    ("25460", "25460"),
                    ("29415", "29415"),
                    ("KEA4", "KEA4"),
                    ("UFA8", "UFA8"),
                    ("UFB3", "UFB3"),
                    ("UGB6", "UGB6"),
                    ("UGB7", "UGB7"),
                    ("UGB9", "UGB9"),
                    ("UIA1", "UIA1"),
                    ("UIA4", "UIA4"),
                    ("UMA2", "UMA2"),
                    ("UMA5", "UMA5"),
                    ("UMA8", "UMA8"),
                    ("UMB8", "UMB8"),
                    ("VEA6", "VEA6"),
                    ("VEA7", "VEA7"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productupdate",
            name="local_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0001", "0001"),
                    ("1000", "1000"),
                    ("10000", "10000"),
                    ("1100", "1100"),
                    ("11000", "11000"),
                    ("14000", "14000"),
                    ("2000", "2000"),
                    ("3000", "3000"),
                    ("4000", "4000"),
                    ("51005", "51005"),
                    ("6000", "6000"),
                    ("7000", "7000"),
                    ("9000", "9000"),
                    ("9500", "9500"),
                    ("BE0026", "BE0026"),
                    ("CAB-1", "CAB-1"),
                    ("FID038", "FID038"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
