# Generated by Django 5.1.4 on 2025-04-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_product_product_key_testss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="test_input",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
