# Generated by Django 5.1.4 on 2025-06-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0004_initial"),
        ("where_to_use", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productupdate",
            name="where_to_use_ref",
            field=models.ManyToManyField(blank=True, to="where_to_use.wheretouse"),
        ),
        migrations.AddField(
            model_name="product",
            name="update_ref",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product",
                to="products.productupdate",
            ),
        ),
    ]
