# Generated by Django 5.1.4 on 2025-04-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_key_test",
        ),
        migrations.AddField(
            model_name="product",
            name="product_key_testss",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
