# Generated by Django 5.1.4 on 2025-04-14 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_remove_product_product_key_testss_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="test_input",
        ),
    ]
