# Generated by Django 5.1.4 on 2025-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_product_key_testss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suppress_event",
            field=models.BooleanField(
                default=False,
                help_text="When true, suppress all EventBridge events on status changes.",
            ),
        ),
    ]
