# Generated by Django 5.1.4 on 2025-04-22 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_product_product_key_testss_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="suppress_event",
        ),
    ]
