# Generated by Django 5.1.4 on 2025-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_remove_product_suppress_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="suppress_event",
            field=models.BooleanField(default=False),
        ),
    ]
