import os

# All environment variables should have their values retrieved here.
# The Python variable name must match the environment variable name.
AWS_ENDPOINT_URL_S3 = os.environ["AWS_ENDPOINT_URL_S3"]
AWS_ENDPOINT_URL_EVENTBRIDGE = os.environ["AWS_ENDPOINT_URL_EVENTBRIDGE"]
DB_NAME = os.environ["DB_NAME"]
DB_HOST = os.environ["DB_HOST"]
DB_USER = os.environ["DB_USER"]
DB_PASSWORD = os.environ["DB_PASSWORD"]
DB_PORT = os.environ["DB_PORT"]
MEDIA_S3_BUCKET_NAME = os.environ["MEDIA_S3_BUCKET_NAME"]
AWS_REGION = os.environ["AWS_REGION"]
APS_API_KEY = os.environ["APS_API_KEY"]
GOV_UK_NOTIFY_API_KEY = os.environ["GOV_UK_NOTIFY_API_KEY"]
OS_ADDRESS_VERIFICATION_API_KEY = os.environ["OS_ADDRESS_VERIFICATION_API_KEY"]
OS_ADDRESS_VERIFICATION_CLIENT_ID = os.environ["OS_ADDRESS_VERIFICATION_CLIENT_ID"]
OS_ADDRESS_VERIFICATION_CLIENT_SCOPE = os.environ[
    "OS_ADDRESS_VERIFICATION_CLIENT_SCOPE"
]
GOV_UK_NOTIFY_EMAIL_TEMPLATE_ID = os.environ["GOV_UK_NOTIFY_EMAIL_TEMPLATE_ID"]
CONTACT_US_TEMPLATE_ID = os.environ["CONTACT_US_TEMPLATE_ID"]
CONTACT_US_APS_EMAIL_ADDRESS = os.environ["CONTACT_US_APS_EMAIL_ADDRESS"]
GOV_UK_NOTIFY_SMS_TEMPLATE_ID = os.environ["GOV_UK_NOTIFY_SMS_TEMPLATE_ID"]
GOV_UK_NOTIFY_API_URL = os.environ["GOV_UK_NOTIFY_API_URL"]
GOV_UK_NOTIFY_UNSUBSCRIBE_URL = os.environ["GOV_UK_NOTIFY_UNSUBSCRIBE_URL"]
APS_TEST_BASE_URL = os.environ["APS_TEST_BASE_URL"]
AZURE_B2C_CLIENT_SECRET_ID = os.environ["AZURE_B2C_CLIENT_SECRET_ID"]
AZURE_B2C_CLIENT_ID = os.environ["AZURE_B2C_CLIENT_ID"]
AZURE_B2C_TENANT_ID = os.environ["AZURE_B2C_TENANT_ID"]
AZURE_B2C_TENANT_NAME = os.environ["AZURE_B2C_TENANT_NAME"]
AZURE_B2C_POLICY_NAME = os.environ["AZURE_B2C_POLICY_NAME"]
AZURE_B2C_JWKS_URI = os.environ["AZURE_B2C_JWKS_URI"]
AZURE_B2C_ISSUER = os.environ["AZURE_B2C_ISSUER"]
OS_ADDRESS_VERIFICATION_BASE_URL = os.environ["OS_ADDRESS_VERIFICATION_BASE_URL"]
OS_ADDRESS_VERIFICATION_TOKEN_URL = os.environ["OS_ADDRESS_VERIFICATION_TOKEN_URL"]
HPUB_FRONTEND_URL = os.environ["HPUB_FRONTEND_URL"]
HPUB_EVENT_BRIDGE_SOURCE = os.environ["HPUB_EVENT_BRIDGE_SOURCE"]
HPUB_EVENT_BRIDGE_BUS_NAME = os.environ["HPUB_EVENT_BRIDGE_BUS_NAME"]
HPUB_EVENT_BRIDGE_DETAIL_TYPE_ORDER_CREATION = os.environ[
    "HPUB_EVENT_BRIDGE_DETAIL_TYPE_ORDER_CREATION"
]
HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_DRAFT = os.environ[
    "HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_DRAFT"
]
HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_ARCHIVE = os.environ[
    "HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_ARCHIVE"
]
HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_WITHDRAWN = os.environ[
    "HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_WITHDRAWN"
]
HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_LIVE = os.environ[
    "HPUB_EVENT_BRIDGE_DETAIL_TYPE_PRODUCT_LIVE"
]
SECRET_KEY = os.environ["SECRET_KEY"]
PUBLIC_KEY = os.environ["PUBLIC_KEY"]
PRIVATE_KEY = os.environ["PRIVATE_KEY"]
DEBUG = os.environ["DEBUG"]
