# Generated by Django 5.1.4 on 2025-04-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diseases", "0001_initial"),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="programs",
            field=models.ManyToManyField(
                blank=True, related_name="diseases", to="programs.program"
            ),
        ),
    ]
