# Generated by Django 5.1.4 on 2025-04-11 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("wagtailcore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "feedback_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "how_satisfied",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("very_satisfied", "Very satisfied"),
                            ("satisfied", "Satisfied"),
                            ("neutral", "Neither satisfied or dissatisfied"),
                            ("dissatisfied", "Dissatisfied"),
                            ("very_dissatisfied", "Very dissatisfied"),
                        ],
                        help_text="How satisfied did you feel about the service?",
                        max_length=50,
                    ),
                ),
                (
                    "would_recommend",
                    models.CharField(
                        blank=True,
                        help_text="Would you recommend the service?",
                        max_length=50,
                    ),
                ),
                (
                    "where_did_you_hear",
                    models.CharField(
                        blank=True,
                        help_text="Where did you hear about this service?",
                        max_length=255,
                    ),
                ),
                (
                    "why_did_you_come",
                    models.CharField(
                        blank=True,
                        help_text="Why did you come to this site?",
                        max_length=255,
                    ),
                ),
                (
                    "did_you_get_what_you_wanted",
                    models.CharField(
                        blank=True,
                        help_text="Did you get what you wanted?",
                        max_length=100,
                    ),
                ),
                (
                    "improve_our_service",
                    models.TextField(
                        blank=True, help_text="How can we improve our service?"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
