# Generated by Django 5.1.2 on 2025-04-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_remove_feedback_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="did_you_get_what_you_wanted",
            field=models.CharField(
                blank=True, help_text="Did you get what you wanted?", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="how_satisfied",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very_satisfied", "Very satisfied"),
                    ("satisfied", "Satisfied"),
                    ("neutral", "Neither satisfied or dissatisfied"),
                    ("dissatisfied", "Dissatisfied"),
                    ("very_dissatisfied", "Very dissatisfied"),
                ],
                help_text="How satisfied did you feel about the service?",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="improve_our_service",
            field=models.TextField(
                blank=True, help_text="How can we improve our service?"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="where_did_you_hear",
            field=models.CharField(
                blank=True,
                help_text="Where did you hear about this service?",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="why_did_you_come",
            field=models.CharField(
                blank=True, help_text="Why did you come to this site?", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="would_recommend",
            field=models.CharField(
                blank=True, help_text="Would you recommend the service?", max_length=50
            ),
        ),
    ]
