# Generated by Django 5.1.4 on 2025-04-30 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventAnalytics",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "event_analytics_id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        max_length=225,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("basket_add", "Basket Add"),
                            ("basket_remove", "Basket Remove"),
                            ("basket_abandoned", "Basket Abandoned"),
                            ("order_completion", "Order Completion"),
                            ("order_abandoned", "Order Abandoned"),
                            ("reorder", "Reorder"),
                            ("download", "Download"),
                        ],
                        max_length=50,
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
