# Generated by Django 5.1.2 on 2025-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventanalytics",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("basket_add", "Basket Add"),
                    ("basket_remove", "Basket Remove"),
                    ("basket_abandoned", "Basket Abandoned"),
                    ("order", "Order"),
                    ("reorder", "Reorder"),
                    ("download", "Download"),
                ],
                max_length=50,
            ),
        ),
    ]
