name: "Build, Test and Release"

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: write
  actions: read

env:
  AWS_REGION: "eu-west-2"
  APP_NAME: "backend"

jobs:
  build:
    name: Build and test container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # Currently pushes to dev but should change to push to prod when account is set up.
    # Even further on, this should push to a centralised ECR registry.
    environment: dev
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Unit tests
        run: |
          # Unit tests are broken at the moment. This step will block in the future.
          cd health_pubs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest || exit 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build container image
        uses: docker/build-push-action@v6
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
          tags: ${{ env.ECR_REGISTRY }}/${{ env.APP_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.APP_NAME }}:latest
          cache-to: type=inline

  release:
    name: Tag and release container image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: dev
    needs:
        - build
    outputs:
      release_tag: ${{ steps.tag_bump.outputs.new_tag }}
      app_image: ${{ steps.push.outputs.app_image }}
      nginx_image: ${{ steps.push.outputs.nginx_image }}
    steps:
      - uses: actions/checkout@v4

      - uses: ukhsa-collaboration/devops-github-actions/.github/actions/github-bump-tag@v0.8.0
        id: tag_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_DEV }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
            role-session-name: retag-image-${{ github.sha }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull, retag, and push Application image for release
        id: push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker pull $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$APP_NAME:$IMAGE_TAG $ECR_REGISTRY/$APP_NAME:${{ steps.tag_bump.outputs.new_tag }}
          docker push $ECR_REGISTRY/$APP_NAME:${{ steps.tag_bump.outputs.new_tag }}
          echo "app_image=$ECR_REGISTRY/$APP_NAME:${{ steps.tag_bump.outputs.new_tag }}" >> $GITHUB_OUTPUT
        
  deploy:
    name: Deploy build to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix:
        environment: ["dev", "qat", "test", "prd"]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
    needs:
      - release
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: deploy-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

    - name: Update Parameter Store with new value
      env: 
        NEW_TAG: ${{ needs.release.outputs.release_tag }}
      run: |
        aws ssm put-parameter --name "/hpub/$APP_NAME/image_tag" --type "String" --value "$NEW_TAG" --overwrite

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition aw-hpub-euw2-${{ matrix.environment }}-ecssvc-$APP_NAME --query taskDefinition > task-definition.json

    - name: Modify Amazon ECS task definition with updated image URI
      id: render-task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: app
        image: ${{ needs.release.outputs.app_image }}
  
    - name: Deploy to Amazon ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.render-task-def.outputs.task-definition }}
        service: aw-hpub-euw2-${{ matrix.environment }}-ecssvc-${{ env.APP_NAME }}
        cluster: aw-hupu-euw2-${{ matrix.environment }}-ecscluster
        wait-for-service-stability: true
  
    - name: Determine Base URL
      id: url
      env:
        environment: ${{ matrix.environment }}
      run: |
        if [ "$environment" == "prd" ]; then
          prefix=hpub
        elif [ "$environment" == "qat" ]; then
          prefix=hpub-qat
        elif [ "$environment" == "test" ]; then
          prefix=hpub-test
        elif [ "$environment" == "dev" ]; then
          prefix=hpub-dev
        else
          echo "Unknown environment. Unable to run tests."
          exit 1
        fi
        echo prefix=$prefix >> $GITHUB_OUTPUT

    - name: End-to-end tests
      if: ${{ matrix.environment }} != "prd"
      env:
        BASE_URL: "https://${{ steps.url.outputs.prefix }}.test-and-trace.nhs.uk"
      run: |
        # No end-to-end testing in place yet
        echo npx playwright test

    - name: Post-Deployment Smoke Test
      env:
        environment_prefix: ${{ steps.url.outputs.prefix }}
      shell: bash
      run: |
        response=$(curl -s -o /dev/null -w "%{http_code}" https://$environment_prefix.test-and-trace.nhs.uk)
        if [ "$response" -ne 200 ]; then
          echo "Post-Deployment tests failed!"
          exit 1
        fi