name: "Build, Test and Release"

on:
  pull_request:
  push:
    branches:
      - "main"
      - "production"
      - "hotfix/upgrading-certifi-package"
    tags:
      - "v*"

permissions:
  id-token: write
  contents: write
  actions: read

env:
  APP_NAME: ${{ vars.APP_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_NAMESPACE: ${{ vars.ECR_NAMESPACE }}
  RUN_UNIT_TESTS: ${{ vars.RUN_UNIT_TESTS }}

jobs:
  build:
    name: Build and test container image
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
      actions: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        if: ${{ env.RUN_UNIT_TESTS == 'true' }}
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Unit tests
        if: ${{ env.RUN_UNIT_TESTS == 'true' }}
        run: |
          cd health_pubs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: build-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build container image
        uses: docker/build-push-action@v6
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          push: ${{ github.event_name == 'push' }}
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:latest
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:latest
          cache-to: type=inline

  release:
    name: Tag and release container image
    runs-on: ubuntu-latest
    if: >
      (github.ref == 'refs/heads/main' ||
       github.ref == 'refs/heads/hotfix/upgrading-certifi-package')
      && github.event_name == 'push'
    environment: dev
    needs:
      - build
    outputs:
      release_tag: ${{ steps.tag_bump.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v4

      - uses: ukhsa-collaboration/devops-github-actions/.github/actions/github-bump-tag@v0.8.0
        id: tag_bump
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: retag-image-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull, retag, and push Application image for release
        run: |
          docker pull ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }}
          docker tag  ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ github.sha }} \
                      ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ steps.tag_bump.outputs.new_tag }}
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ steps.tag_bump.outputs.new_tag }}

  deploy_to_nonprod:
    name: Deploy to dev + test
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    needs: release
    strategy:
      matrix:
        environment: ["dev", "test"]
    if: >
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/main' ||
       github.ref == 'refs/heads/hotfix/upgrading-certifi-package')

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: deploy-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Parameter Store with new value
        env:
          NEW_TAG: ${{ needs.release.outputs.release_tag }}
        run: |
          aws ssm put-parameter \
            --name "/hpub/$APP_NAME/image_tag" \
            --type "String" \
            --value "$NEW_TAG" \
            --overwrite

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition aw-hpub-euw2-${{ matrix.environment }}-ecssvc-$APP_NAME \
            --query taskDefinition > task-definition.json

      - name: Modify ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: ${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ needs.release.outputs.release_tag }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: aw-hpub-euw2-${{ matrix.environment }}-ecssvc-${{ env.APP_NAME }}
          cluster: aw-hpub-euw2-${{ matrix.environment }}-ecscluster
          wait-for-service-stability: true

  deploy_to_upper_envs:
    name: Deploy to uat / preprod / prod
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ matrix.environment }}
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        environment: ["uat", "preprod", "prod"]

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: release-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Parameter Store with release tag
        run: |
          aws ssm put-parameter \
            --name "/hpub/$APP_NAME/image_tag" \
            --type "String" \
            --value "${GITHUB_REF#refs/tags/}" \
            --overwrite

      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition aw-hpub-euw2-${{ matrix.environment }}-ecssvc-$APP_NAME \
            --query taskDefinition > task-definition.json

      - name: Render task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: ${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${GITHUB_REF#refs/tags/}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: aw-hpub-euw2-${{ matrix.environment }}-ecssvc-${{ env.APP_NAME }}
          cluster: aw-hpub-euw2-${{ matrix.environment }}-ecscluster
          wait-for-service-stability: true
