name: Continuous Deployment (CD)

on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step to install dependencies using the composite action
      - id: install_dependencies
        name: Install Dependencies
        uses: ./.github/workflows/install-dependencies-action

      # Step to format and lint Python code
      - name: Format and Lint Python Code
        run: |
          cd hpub-backend/backend_alpha
          black .  # Formatting with Black
          isort .   # Sorting imports with isort

      # Step to run Python unit tests
      - name: Run Python Unit Tests
        run: |
          cd hpub-backend/backend_alpha
          pytest  # Running unit tests with pytest

      # Step to lint React code
      - name: Lint React Code
        run: |
          cd hpub-frontend
          npx eslint .  # Linting with ESLint

      # Step to run unit tests for the React frontend
      - name: Run React Unit Tests
        run: |
          cd hpub-frontend
          npm test  # Running unit tests

      # Step to deploy both Python and React apps
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # TODO: Add your deployment commands here.
          # This could include Docker commands, server restart commands, or any other deployment logic.
