name: Build, Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - DevOps_test
  pull_request:
    branches:
      - main
      - DevOps_test
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        options:
          - dev
          - test
          - uat
          - prod
          - frontend
          - backend          

env:
  AWS_REGION: "eu-west-2"
  DOCKER_COMPOSE_PATH: hpub-backend
  ECR_REPOSITORY_BASE: "aws-hpub-eu-west-2"  
  AWS_TEST_ACCOUNT_ID: ${{ secrets.AWS_TEST_ACCOUNT_ID }}
  AWS_TEST_ACCESS_KEY_ID: ${{ secrets.AWS_TEST_ACCESS_KEY_ID }}
  AWS_TEST_SECRET_ACCESS_KEY: ${{ secrets.AWS_TEST_SECRET_ACCESS_KEY }}  
  AWS_UAT_ACCOUNT_ID: ${{ secrets.AWS_UAT_ACCOUNT_ID }}
  AWS_UAT_ACCESS_KEY_ID: ${{ secrets.AWS_UAT_ACCESS_KEY_ID }}
  AWS_UAT_SECRET_ACCESS_KEY: ${{ secrets.AWS_UAT_SECRET_ACCESS_KEY }}   

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    if: ${{ github.event.inputs.environment == 'test' }}
    steps:
    # Step 1: Checkout Code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Set Environment Variables Based on Input
    - name: Set Environment Variables
      id: set-env
      run: |
        echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-dev-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
          echo "AWS_ACCOUNT_ID={{ env.AWS_TEST_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID={{ env.AWS_TEST_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY={{ env.AWS_TEST_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-test-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
          echo "AWS_ACCOUNT_ID={{ env.AWS_UAT_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID={{ env.AWS_UAT_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY={{ env.AWS_UAT_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-uat-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_PROD_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_PROD_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-prod-backend" >> $GITHUB_ENV
        else
          echo "Invalid environment selected"
          exit 1
        fi

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_TEST_ACCOUNT_ID }}:role/${{ github.event.inputs.environment }}-github-oidc
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
               

  
    # Step 4: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      id: build-image
      run: |
        cd ${{ env.DOCKER_COMPOSE_PATH }}
        docker compose -f docker-compose.yaml build
        docker images
        docker tag docker.io/library/hpub-backend-web \
        ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2
        docker images
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2
         
        echo "image=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2" >> $GITHUB_OUTPUT
        
    - name: Build and Push Docker Image
      id: build-front-image
      run: |
          cd hp-frontend
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1 .
          docker images
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1
           
          echo "image=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1" >> $GITHUB_OUTPUT
                
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition aws-hpub-eu-west-2-test-backend --query taskDefinition > task-definition.json           
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: my-container
        image: ${{ steps.build-image.outputs.image }}
  
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: aws-hpub-eu-west-2-test-backend
        cluster: aws-hpub-eu-west-2-test-ecs-cluster
        wait-for-service-stability: true  

  deploy_uat:
    runs-on: ubuntu-latest
    environment: uat
    if: ${{ github.event.inputs.environment == 'uat' }}
    steps:
    # Step 1: Checkout Code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Set Environment Variables Based on Input
    - name: Set Environment Variables
      id: set-env
      run: |
        echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
        if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_DEV_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-dev-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "test" ]; then
          echo "AWS_ACCOUNT_ID={{ env.AWS_TEST_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID={{ env.AWS_TEST_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY={{ env.AWS_TEST_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-test-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "uat" ]; then
          echo "AWS_ACCOUNT_ID={{ env.AWS_UAT_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID={{ env.AWS_UAT_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY={{ env.AWS_UAT_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-uat-backend" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
          echo "AWS_ACCOUNT_ID=${{ secrets.AWS_PROD_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_PROD_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ECR_REPOSITORY=aws-hpub-eu-west-2-prod-backend" >> $GITHUB_ENV
        else
          echo "Invalid environment selected"
          exit 1
        fi

    # Step 3: Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_UAT_ACCOUNT_ID }}:role/${{ github.event.inputs.environment }}-github-oidc
        role-session-name: samplerolesession
        aws-region: ${{ env.AWS_REGION }}
        aws-access-key-id: ${{ steps.set-env.outputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ steps.set-env.outputs.AWS_SECRET_ACCESS_KEY }}
               

  
    # Step 4: Log in to Amazon ECR
    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      id: build-image
      run: |
        cd ${{ env.DOCKER_COMPOSE_PATH }}
        docker compose -f docker-compose.yaml build
        docker images
        docker tag docker.io/library/hpub-backend-web \
        ${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2
        docker images
        docker push ${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2
         
        echo "image=${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:test2" >> $GITHUB_OUTPUT
        
    - name: Build and Push Docker Image
      id: build-front-image
      run: |
          cd hp-frontend
          docker build -t ${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1 .
          docker images
          docker push ${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1
           
          echo "image=${{ env.AWS_UAT_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:frontend1" >> $GITHUB_OUTPUT
                
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition aws-hpub-eu-west-2-uat-backend --query taskDefinition > task-definition.json           
    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: app
        image: ${{ steps.build-image.outputs.image }}
  
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: aws-hpub-eu-west-2-uat-backend
        cluster: aws-hpub-eu-west-2-uat-ecs-cluster
        wait-for-service-stability: true

        
