name: Black Formatter Check with ReviewDog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set environment variables
        run: |
          echo "REPORTER=${{ github.event_name == 'pull_request' && 'github-pr-review' || 'github-check' }}" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black==23.1.0

      - name: Run Black with ReviewDog
        uses: reviewdog/action-black@644053a260402bc4278a865906107bd8aef7fae8 # v3
        with:
          black_args: "--check"
          reporter: ${{ env.REPORTER }}
          filter_mode: 'nofilter'
          workdir: 'health_pubs'
          github_token: ${{ secrets.GITHUB_TOKEN }}
