name: "Deploy and release to Prod"

on:
  release:
    types: [published]

env:
  APP_NAME: ${{ vars.APP_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_NAMESPACE: ${{ vars.ECR_NAMESPACE }}
  RUN_UNIT_TESTS: ${{ vars.RUN_UNIT_TESTS }}
  BASE_URL: ${{ vars.FPHR_BASE_URL }}

jobs:
  deploy_to_prod:
    name: Deploy build to Prod
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix:
        environment: ["dev","prod"]

    permissions:
      contents: write
      id-token: write
      actions: read
    steps:
  
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: deploy-${{ github.sha }}
          aws-region: ${{ env.AWS_REGION }}
     
      - name: Get Release Tag
        run: echo "Release tag is ${{ github.event.release.tag_name }}"

      # docker pull + tag + push
      - name: Login to Amazon ECR
        if: ${{ matrix.environment == 'dev' }}
        id: login-ecr-release
        uses: aws-actions/amazon-ecr-login@183a1442edf41672e66566b7fc560e297a290896 # v2

      - name: Pull, retag, and push Application image for prod
        if: ${{ matrix.environment == 'dev' }}
        id: ecr-tag-prod
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-release.outputs.registry }}
        run: |
          # Pull the PREPROD image (the last promoted artefact)
          docker pull $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:preprod-${{ github.event.release.tag_name }}

          # Retag it for PROD
          SRC="$ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:preprod-${{ github.event.release.tag_name }}"
          docker tag "$SRC" "$ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:prod-${{ github.event.release.tag_name }}"
          docker tag "$SRC" "$ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:latest"

          # Push the PROD image to ECR
          docker push $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:prod-${{ github.event.release.tag_name }}
          docker push $ECR_REGISTRY/$ECR_NAMESPACE/$APP_NAME:latest

        
      - name: Update Parameter Store with new value
        if: ${{ matrix.environment == 'prod' }}
        env:
          NEW_TAG: ${{ matrix.environment }}-${{ github.event.release.tag_name }}
        run: |
          aws ssm put-parameter \
            --name "/hpub/$APP_NAME/image_tag" \
            --type "String" \
            --value "$NEW_TAG" \
            --overwrite

      - name: Download ECS Task Definition
        if: ${{ matrix.environment == 'prod' }}
        run: |
          aws ecs describe-task-definition \
            --task-definition aw-hpub-euw2-${{ matrix.environment }}-ecssvc-$APP_NAME \
            --query taskDefinition \
            > task-definition.json

      - name: Modify ECS Task Definition Image
        if: ${{ matrix.environment == 'prod' }}
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@77954e213ba1f9f9cb016b86a1d4f6fcdea0d57e # v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: ${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_NAMESPACE }}/${{ env.APP_NAME }}:${{ matrix.environment }}-${{ github.event.release.tag_name }}

      - name: Deploy to Amazon ECS
        if: ${{ matrix.environment == 'prod' }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@fc8fc60f3a60ffd500fcb13b209c59d221ac8c8c # v2
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: aw-hpub-euw2-${{ matrix.environment }}-ecssvc-${{ env.APP_NAME }}
          cluster: aw-hpub-euw2-${{ matrix.environment }}-ecscluster
          wait-for-service-stability: true

      - name: End-to-end tests
        if: ${{ matrix.environment != 'prod' && matrix.environment != 'preprod' }}
        env:
          BASE_URL: ${{env.BASE_URL}}
        run: |
          # No end-to-end testing in place yet
          echo npx playwright test

      - name: Post-Deployment Smoke Test
        if: ${{ matrix.environment == 'prod' }}
        run: |
          response=$(curl -H "user-agent: Mozilla/5.0 (compatible; PostDeploymentHealthCheck)" -s -o /dev/null -w "%{http_code}" ${{env.BASE_URL}}/api/v1/health/)
          if [ "$response" -ne 200 ]; then
            echo "Post-deployment smoke test FAILED!"
            exit 1
          fi
