name: SonarCloud Scan
on:
  push:
    branches:
      - main
      - feature*
      - backend*
      - frontend*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

#      - name: Run Tests and Generate Coverage
#        continue-on-error: true
#        run: |
#          npm install
#          npm test

      - name: SonarCloud Scan
        if: always()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
