name: Update User role

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation or update

  workflow_dispatch:  # This enables manual triggering
    inputs:
      email:
        description: "User email address"
        required: true
        type: string

jobs:
  update-role:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Update User role to admin
        run: |
          cd health_pubs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd core/users/management/commands
          ls -lar
          python manage.py update_user_role ${{ inputs.email }}
