name: Update User role

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR creation or update

  workflow_dispatch:  # This enables manual triggering
    inputs:
      email:
        description: "User email address"
        required: true
        type: string

env:
  APP_NAME: ${{ vars.APP_NAME }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  ECR_NAMESPACE: ${{ vars.ECR_NAMESPACE }}
  RUN_UNIT_TESTS: ${{ vars.RUN_UNIT_TESTS }}

jobs:
  update-role:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            # AWS_ACCOUNT_ID_ECR_REGISTRY is used for pulling from a shared ECR repository
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_ECR_REGISTRY }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
            role-session-name: retag-image-${{ github.sha }}
            aws-region: ${{ env.AWS_REGION }}

      - name: Run Update User role to admin
        run: |
          cd health_pubs
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          ls -lar
          python manage.py update_user_role ${{ inputs.email }}
